### ISSUE TITLE
This package breaks Chakra-UI Toasts.

### ISSUE THREAD

**Issue by OmkarK45** [mustaphaturhan/chakra-ui-markdown-renderer#2] opened 2020-10-13 13:08 UTC
Hey there, 

I tried this package to render the markdown sent by the server, but apparently, it breaks the functionality of the native toast component in Chakra-UI. 
 Here's the error code.
`can't perform a react state update on an unmounted component. this is a no-op, but it indicates a memory leak in your application. to fix, cancel all subscriptions and asynchronous tasks in the componentwillunmount method. ToastManager`

You can check the above behavior here. [Here](https://github.com/OmkarK45/blog-app) .

**Comment by mustaphaturhan** [comment] 2020-10-13 13:54
Hey @OmkarK45, thank you for your feedback.

I looked to your problem and you're right. There is something wrong with ToastManager when I import `chakra-ui-markdown-renderer` and I can see the problem even I don't use renderer in anywhere. I think the problem is related with library webpack configs so I will look it later.

I can suggest a workaround at the moment. Instead of this library, you can use this renderer directly from https://github.com/mustaphaturhan/chakra-ui-markdown-renderer/blob/master/src/index.js.

Just download raw file and use like a regular react component. Import from local files instead of chakra-ui-markdown-renderer while I look what causing the problem.

**Comment by OmkarK45** [comment] 2020-10-13 15:35
Update: It worked using the said method. Again, thanks!

**Comment by pjtf93** [comment] 2020-11-02 23:59
Thank you for this @mustaphaturhan , it helped me a lot!

**Comment by mustaphaturhan** [comment] 2020-12-16 08:33
Hey guys.

This issue fixed with `chakra-ui-markdown-renderer` v1.0.0. Do not forget to update your @chakra-ui version before update `chakra-ui-markdown-renderer`.

**Closed by mustaphaturhan** 2020-12-16 08:33 UTC
